export default () => {
    return (
        <>
        <div className="bg-white p-8 rounded-xl shadow-lg">
        <h1 className="text-4xl text-center font-bold p-10 pb-12 text-shadow">Welcome to AvondaleSDA</h1>
        <p className='text-1xl text-gray-800'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam molestias laudantium sequi mollitia consequuntur tenetur necessitatibus dolorum, quos id delectus reprehenderit fuga ipsam sed minima suscipit nihil voluptas nulla nostrum!
          Libero deleniti quibusdam doloribus ab a dolores consequatur quam cupiditate totam eum repudiandae tempore ad, commodi minima eaque officia saepe ratione eveniet magnam voluptatum nesciunt. Saepe molestias corporis eum rerum.
          Quia nihil molestiae cum delectus aliquid repudiandae vitae dolor voluptatum alias itaque unde dicta, iste eum? Dicta accusamus, facilis temporibus saepe dolores autem perspiciatis dignissimos hic voluptate facere quisquam nostrum!
          Magnam tempora aperiam iusto architecto illo sequi impedit numquam, nesciunt fugit non, necessitatibus alias porro voluptas, reiciendis repudiandae unde! Mollitia, quos non laborum omnis fugit consequatur cum? Explicabo, ipsa quo.
          Beatae, cupiditate nostrum esse voluptatum ab ut corporis tempora pariatur sit dicta ratione odio iusto commodi neque non dolorem possimus placeat dolor? Est maxime consectetur ipsa enim aspernatur optio molestias?
          Inventore perferendis quidem odit assumenda neque quam quae expedita, placeat animi officiis voluptatibus unde quisquam atque, nemo ea molestias quos aut, nulla voluptate autem perspiciatis officia. Harum adipisci vitae commodi.
          Voluptatibus sint tempora molestias at maiores nesciunt praesentium assumenda dolor, veniam animi dicta libero quo. Eligendi, reiciendis nam. A vero architecto ab ad incidunt. Odio suscipit non aliquid rerum ipsa.
          Natus ullam quae quibusdam a eaque magnam laborum inventore enim. Veniam ab totam pariatur optio dolorem corporis tempora, eius natus numquam, ullam aperiam et, culpa error in ipsa iste ducimus!
          Eum consectetur maiores recusandae quibusdam eos perspiciatis reiciendis veritatis quasi, porro ad. Non commodi molestiae repellendus veritatis dignissimos! Eos quas esse adipisci, nulla veniam odio fugit ipsam culpa voluptatum ipsum!
          Sunt maxime reprehenderit ad veniam ab nemo quam ipsa animi, perspiciatis, asperiores eveniet aspernatur aperiam assumenda doloremque dolorum debitis cum voluptatum totam neque dignissimos enim suscipit? Ut repellendus accusamus est.
          Laboriosam, quas nam. Fugit ad ut ducimus sapiente modi quo deserunt quae adipisci cupiditate mollitia dolor alias odio distinctio, maiores quas reprehenderit. Dicta repellendus dolor tempora sunt laudantium provident aut!
          Delectus tempore optio dolore vel architecto. Fuga, totam hic ipsa at fugit, culpa velit vitae nisi dicta distinctio molestiae voluptatem. Doloremque quo unde, in ipsam molestiae exercitationem magnam explicabo deserunt!
          Neque quidem hic maiores! Nulla consequuntur, aliquam enim facere debitis commodi eligendi dignissimos illo mollitia asperiores blanditiis repellendus doloribus explicabo quidem optio reprehenderit labore tempora cum iusto? Quam, atque voluptate!
          Molestiae quidem quae nesciunt. Fuga voluptatum impedit id soluta facilis error, laudantium quidem qui non repudiandae quia exercitationem minus? Pariatur eligendi architecto omnis minus exercitationem, perspiciatis magni aliquam rem iste!
          Nisi eaque perspiciatis non quasi aut unde, velit deleniti cumque nostrum! Nulla sit fugit saepe maxime debitis possimus eveniet deleniti recusandae quibusdam dolorum quod provident ipsa, repellendus, laborum modi omnis?
          Magni quis, pariatur ratione alias beatae non. Officiis voluptas ipsa aliquam. Quis, culpa? Esse culpa architecto illo, tempora accusantium aspernatur consequatur molestiae repellat dolore a iusto sunt incidunt, consequuntur sint.
          Aspernatur, quas! Sunt doloremque corrupti in, ratione deserunt, quae illo nisi consequuntur dolores totam laudantium sit numquam, aspernatur ullam laborum voluptates! Suscipit doloremque non magni quaerat qui! Recusandae, nemo voluptatibus!
          Sequi, doloremque illum? Deleniti ad, quam facilis omnis nesciunt culpa veniam labore sequi molestiae. Cum omnis quia quidem magnam, minima, vitae excepturi nulla numquam quas ipsam blanditiis? Neque, numquam ratione!
          Voluptatibus facere atque recusandae neque eos? Rerum numquam id molestias deserunt neque, quae quisquam sequi vitae architecto, nulla repellendus! Rerum similique fuga mollitia ipsum natus. Minus obcaecati iste non eos?
          Tempore nisi est nesciunt iure iste vel asperiores sint ratione voluptatem libero, velit quia ut in animi eaque molestiae error temporibus ad itaque perferendis aliquam provident atque. Rerum, repellat ad!
          Maxime neque hic asperiores libero ratione delectus quaerat corrupti excepturi, consequatur a perspiciatis id culpa itaque. Corporis explicabo sapiente officia, nulla cumque neque dignissimos ab, est quae commodi nobis dolor.
          Saepe cumque laborum dolore labore dolor, expedita perferendis explicabo voluptatem ad tempora nobis. Possimus neque nulla, adipisci ducimus aperiam aspernatur? Minus id alias dolore minima maxime, veniam molestias dolor eligendi?
          Nihil quas quam atque nesciunt, quod porro aliquam vitae? Delectus, numquam reiciendis. Quos, explicabo iusto itaque illo illum veniam ut unde. Delectus, accusantium porro. Minus ut expedita perferendis deleniti iure?
          Molestias illum amet deleniti dolores mollitia expedita tenetur corporis sunt eius ut perspiciatis, quae aliquam rem quam cum facere ducimus maiores, optio qui dolorem voluptates dignissimos? Maiores dolorum debitis pariatur.
          Esse obcaecati distinctio dicta odit vero optio reprehenderit quaerat tempore nemo similique ex quod nesciunt deleniti blanditiis alias ab corporis, consequatur laudantium ad magni explicabo quos. Illum ipsam animi corrupti!
          Ut reiciendis suscipit, temporibus sapiente voluptates soluta, obcaecati necessitatibus ipsum quae qui voluptatem! Tempore laudantium minima minus, praesentium iure, voluptatum nihil modi architecto sequi est error corrupti! Eveniet, praesentium numquam.
          Praesentium molestiae delectus provident. Placeat, architecto fuga? Nostrum, quos placeat necessitatibus obcaecati aspernatur neque deserunt eum distinctio repudiandae tenetur reiciendis tempore ipsa vero, odio praesentium, culpa doloribus alias. Asperiores, iusto!
          Est eum laborum nisi non debitis. Aperiam temporibus debitis cum dolore, dolorum provident, eaque autem id consectetur explicabo accusamus? Porro dolorum quia magnam velit quaerat illum vero similique? Numquam, eos?
          Natus omnis numquam cum dolores veniam ab aliquam voluptates blanditiis libero, rerum quam corrupti fuga maxime obcaecati eum culpa odit expedita eius ipsum! Eos doloremque hic sint, omnis quaerat obcaecati?
          Hic, fugit voluptatibus rerum fuga tempore rem dolor. Minus eveniet vero amet numquam, adipisci distinctio iusto id, natus nisi, non ullam et nemo cupiditate harum asperiores in quis sed voluptas!
          Recusandae nesciunt consequuntur voluptates aut, placeat est sequi voluptatum dicta deleniti hic temporibus, qui mollitia ipsum corrupti nam omnis magnam animi dignissimos harum, tempora iste vitae earum! In, beatae reiciendis?
          Deleniti incidunt explicabo nam atque, magnam veritatis rerum eaque recusandae, magni voluptatum sit nostrum a fugit maiores aliquid, dolores voluptate illum unde aperiam exercitationem nesciunt? Quidem perferendis recusandae et dolorem.
          Nesciunt earum nostrum possimus illum enim adipisci, nobis hic explicabo dicta sed quos aut fuga odio neque minus odit corporis, ipsa veniam aperiam quisquam dolorem soluta expedita vero est! Fuga.
          Nemo quos modi reiciendis vero sint cumque blanditiis nostrum, inventore ab! Officiis optio neque provident est amet doloremque, delectus iure, fugit pariatur eum atque quibusdam porro. Numquam adipisci explicabo amet.
          Voluptatibus veniam veritatis autem possimus facere vero ad ut vitae, cupiditate blanditiis. Accusamus, itaque beatae facere sint numquam quam quas, expedita commodi impedit unde, eum harum. Illo omnis ducimus est.
          Voluptatem repudiandae, atque quod similique ipsam minus vel ipsa quo dolorem accusantium optio praesentium voluptatum fugiat sequi dicta numquam, rem in nam minima molestiae tempore! Atque debitis aspernatur reiciendis at.
          Libero quae, eaque eligendi harum, officiis facilis aut fuga culpa minima incidunt debitis aspernatur eius blanditiis deserunt voluptates modi quaerat ipsam quod aliquid quo tempora tenetur nihil omnis. Voluptate, non!
          Cumque quas corporis ipsa consectetur. Laborum fugit ratione et repellat qui alias accusantium natus voluptates. Quo esse dignissimos corporis, eos quasi, ipsam consectetur voluptatum, explicabo minima nam porro necessitatibus similique.
          Doloremque doloribus nihil nisi ut illum impedit possimus quidem atque illo exercitationem, obcaecati itaque labore rerum reprehenderit omnis. Quos eum amet necessitatibus ipsa nam voluptate itaque libero harum facere aliquid?
          Aperiam, iste architecto totam beatae minima libero optio eligendi quasi ea sequi velit soluta magnam similique asperiores tempore quos recusandae enim aut voluptatibus vero quo, mollitia fugit ut! Iusto, quasi?
          Veniam voluptates minima eveniet eum tempore harum illum est? Provident nobis labore, deleniti minus dolor expedita excepturi libero quos magnam cumque beatae vitae incidunt mollitia ex adipisci quas distinctio soluta?
          Accusamus, tempore? Repellat soluta cum pariatur alias amet laudantium ipsam hic reiciendis, voluptate porro ducimus accusamus repellendus fugit quia aspernatur perspiciatis qui tempora ullam aliquid odio eligendi explicabo omnis deleniti.
          Veniam minus repudiandae quo! Facilis eum placeat eaque excepturi alias voluptas corporis omnis, magnam a quaerat voluptatem pariatur blanditiis porro, ad quae officiis perferendis ut iste provident. At, eos aut.
          Sint, praesentium id quo cupiditate provident molestiae officiis ad pariatur, aperiam, autem ratione tempora obcaecati suscipit fugiat aliquam sit eum sed nesciunt sunt perspiciatis? Quo facilis nihil exercitationem amet distinctio!
          Libero distinctio enim esse odit ipsa voluptatibus earum deleniti tempora, eius ipsum saepe accusantium ut aperiam vitae molestiae rerum, nihil magni natus error nam illum! Sed id nemo ut itaque.
          Debitis quasi qui voluptates laboriosam modi! Nobis, exercitationem autem. Reiciendis optio illo dolore ex incidunt temporibus similique numquam accusamus neque odit adipisci rerum alias molestias explicabo, eveniet, ad nostrum iusto?
          Voluptatum delectus corrupti officia magni explicabo suscipit dolor, nesciunt reiciendis eius atque quo debitis placeat eaque maxime velit at molestiae. Cumque in vitae ratione consequatur! Necessitatibus explicabo nisi velit accusantium?
          Ad asperiores totam delectus aliquid. Itaque earum expedita unde molestiae minus dolor necessitatibus exercitationem placeat quam, delectus, maiores vero ipsam voluptate magni. A fuga voluptatibus nesciunt rem, dolorem id quibusdam.
          Perspiciatis neque minima commodi soluta maiores. Quidem officiis doloribus non cum deleniti facilis nulla vel dolor alias, quas ipsa eligendi inventore suscipit doloremque libero aliquid, accusamus veniam quasi obcaecati velit!
          Consequatur repellat doloremque harum earum magni sequi deleniti aspernatur quos, fugiat ex quod molestiae minima animi neque iusto tempora reprehenderit doloribus. Saepe, mollitia. Velit debitis dolores atque dolor, impedit rem.
          Alias, veritatis. Molestiae expedita officiis nemo laudantium itaque ducimus quod fuga! Ipsum praesentium at laborum libero omnis quod aut, perferendis facilis dolorum reiciendis quidem accusamus tempore blanditiis aliquid, quia delectus!
          Ipsum, voluptatibus ut sed distinctio inventore dignissimos tempore, accusantium laboriosam culpa amet unde dolorum nam obcaecati nisi facere deserunt harum. Ab molestias rem delectus debitis facilis omnis iste, voluptas totam!
          Reiciendis blanditiis aliquid officia, dolor, eligendi maiores earum consequuntur exercitationem vel voluptates id eius impedit debitis optio provident eum et qui sunt commodi, corrupti vero beatae? Reprehenderit magni sint adipisci!
          Tempore fuga, a obcaecati nesciunt atque harum! Perferendis eveniet, animi adipisci totam quisquam, veritatis id repellendus iure suscipit magni provident nulla culpa iste at? Porro qui doloribus voluptatum labore maxime!
          Ipsum minima totam odit, laboriosam repudiandae deleniti est iste voluptates dolore ducimus molestiae omnis ut ex, quibusdam quas culpa iusto. Odit recusandae molestiae voluptatem vitae blanditiis enim accusamus quia delectus.
          Earum, officia asperiores non fugiat obcaecati repudiandae saepe aliquid dolore ad, praesentium fuga cumque. Deserunt magnam, beatae odio natus, repellendus totam, laudantium ipsam voluptatum inventore quibusdam molestiae atque similique accusantium.
          Possimus vel repudiandae animi ipsum distinctio similique rerum mollitia cupiditate asperiores ipsam sit quia fuga, magni at cum ullam expedita amet eligendi delectus aut quasi ex. Nihil quasi consequuntur natus.
          Optio maxime eaque soluta, ipsa, aperiam fugit consequuntur minima impedit rerum enim dolorem at earum nihil non nostrum voluptate dolorum nisi omnis praesentium perspiciatis, quos quo? Facere atque labore odio?
          Officiis placeat eveniet exercitationem laudantium distinctio rem tenetur voluptatem, totam sapiente. Aperiam nisi ex accusamus nostrum expedita, itaque, recusandae, eos neque natus odit magnam architecto sapiente quidem sunt perferendis est!
          Aperiam perferendis optio maxime eius debitis aliquid hic veritatis deleniti sed. Dignissimos vel, temporibus quo voluptates asperiores qui magni, iusto officiis modi et ipsum. Facilis quos ipsam fuga libero tempora.
          Mollitia debitis temporibus cupiditate voluptatem tempore quasi dolore, culpa illum ducimus natus amet quae nulla quod aliquid veniam perspiciatis architecto ratione nihil aspernatur veritatis libero! Cum adipisci pariatur perspiciatis quis!
          Deleniti illum libero, non ea similique in excepturi facere quibusdam asperiores? Recusandae cum labore exercitationem consectetur ex eaque voluptatibus in ipsum eum voluptatem earum, esse temporibus nostrum eligendi corporis veritatis.
          Doloribus esse deserunt assumenda error qui magnam explicabo necessitatibus pariatur obcaecati ad! Eos, ipsam natus. Aperiam laudantium iure unde repudiandae ullam quia distinctio molestiae blanditiis, laboriosam voluptates non commodi odit?
          Labore odio reiciendis magni ullam quam aliquam dolor soluta, fugit officia totam ducimus perspiciatis quod quibusdam nihil repudiandae tempora ut aliquid? Praesentium ducimus incidunt exercitationem officiis, expedita voluptatem aspernatur mollitia.
          Totam nobis ipsum esse, voluptate adipisci fuga incidunt sed voluptatum. Totam amet corrupti eius similique consequatur sed. Fugit neque voluptatum placeat ad incidunt minima alias, quibusdam ducimus corporis molestiae magni.
          Quasi nihil suscipit maiores delectus corporis aut magni natus officia aperiam at totam dolores, beatae ea unde officiis inventore? Recusandae rem soluta maiores modi sequi porro nemo mollitia quod perferendis.
          Dolorum labore, consectetur illum id consequuntur tempore in necessitatibus iste sint dolor modi, eligendi repudiandae harum repellendus officiis quaerat voluptas ex pariatur optio exercitationem obcaecati? Repellat harum illo rerum ab!
          Nostrum perspiciatis suscipit voluptatibus autem corrupti, perferendis hic quisquam quidem sint reiciendis distinctio incidunt deserunt harum voluptas in soluta accusamus consequuntur excepturi aliquam minus necessitatibus nisi vitae. Nemo, mollitia distinctio!
          Provident consequatur magnam ex, beatae architecto et mollitia rerum quis culpa maxime obcaecati? Laudantium eum autem, odio sit ad quod, id vel velit molestias aut non perspiciatis doloremque, nostrum voluptatem.
          Cum temporibus alias inventore, nihil iusto suscipit consequatur labore mollitia minima tempore repellendus quae, ipsa repudiandae modi necessitatibus, dolorum ipsam animi harum quidem dolore officiis magnam! Mollitia consequatur autem dolore!
          Ex fugit consequuntur temporibus velit. Modi laboriosam enim non, culpa quidem debitis adipisci labore tempora inventore perferendis dolorum corrupti tenetur excepturi itaque veritatis numquam, voluptas consequuntur fugiat, eum unde a?
          Minus saepe voluptas officia odit natus a assumenda provident quia quo illum magnam impedit laborum, quae eaque numquam, optio mollitia rem totam sunt atque deserunt reiciendis dolore? Assumenda, non velit.
          Quas reiciendis quos alias pariatur laborum temporibus est necessitatibus libero veniam? Necessitatibus illum accusamus nulla corrupti eligendi blanditiis quas maxime deleniti dolorem aspernatur, ex aut amet? Repellendus repudiandae eius magni.
          Facere iste deserunt vitae dolorem, deleniti pariatur quod molestias tenetur corporis placeat quibusdam. Quod, dicta. Similique asperiores illo porro eius. Laborum nihil laudantium dolore quod saepe corporis, consectetur odit cumque?
          Possimus, delectus ipsam excepturi cum accusantium numquam ducimus necessitatibus earum laboriosam voluptatem culpa dolores? Nostrum, velit maxime sed officia corporis eveniet minus sint optio! Suscipit vel nam explicabo ex architecto?
          Eum obcaecati vel ab nisi, labore dicta. Nisi, cupiditate eligendi facere repudiandae suscipit aliquid. Fuga, ipsam debitis nobis, quam dolores id est reiciendis a sapiente soluta aperiam repellendus eum earum.
          Hic iste recusandae similique aliquam quidem itaque consequatur inventore impedit porro. Maxime quod nemo architecto sunt explicabo reprehenderit, at, nesciunt beatae voluptatum rem iusto quam delectus consequuntur id. Provident, exercitationem!
          Nulla laboriosam rerum impedit ipsa amet nesciunt voluptas quia maxime aspernatur ducimus! Laudantium veniam reprehenderit qui animi quis porro fugit aut, assumenda alias facilis omnis nobis ipsam esse cupiditate quod.
          Atque, magni. Omnis officiis architecto sunt esse provident non laudantium quibusdam tempora repudiandae minus dolorum quisquam quidem nihil vel cum nulla quam explicabo rem id eligendi eveniet, blanditiis enim. Beatae!
          Cupiditate, nobis ex. Rem at obcaecati, id nam maiores iure tempora repellat dolore assumenda, quia nesciunt fugiat soluta non commodi necessitatibus veritatis expedita? Ad voluptates aliquid, ab quaerat architecto aliquam.
          Animi rem laudantium omnis recusandae minus. Natus, illum nisi, magni est optio rem ea voluptate sed facere eum necessitatibus qui exercitationem dolores dicta odio sit, dolore deleniti quas laudantium ullam?
          Odio cupiditate maiores, dignissimos, obcaecati nisi magni architecto possimus nam blanditiis veritatis ullam deserunt veniam. Tempore nesciunt sint a sequi obcaecati necessitatibus est, laboriosam in libero accusantium veritatis aliquid quasi!
          Quos corporis eveniet sapiente, eum minus dignissimos architecto maxime reprehenderit, ipsum nam sequi et vitae voluptatem sint est assumenda dolor sit! Ut quam animi blanditiis est commodi. Saepe, eos iusto!
          Modi neque aut et minus ducimus? Corrupti harum eveniet reiciendis iure itaque cupiditate, laborum maiores voluptatibus architecto reprehenderit! Qui ipsam veritatis illo similique voluptates itaque quae maxime consectetur, praesentium inventore?
          Fuga alias nemo tempore, ut quibusdam quia mollitia rem aut nulla repellat eligendi dolores, cum sequi. Nulla eum ex ipsam harum quod vitae temporibus reiciendis unde ea? Excepturi, eveniet earum?
          Iusto maiores facere, nulla numquam vel itaque eum. Beatae, quas atque autem necessitatibus fuga exercitationem! Tempora, fuga perspiciatis! Sapiente, voluptatibus eos vel alias vitae ex nam eum illum recusandae cum!
          Unde eveniet dignissimos error. Aliquid veritatis doloribus, voluptas nisi, ratione beatae nihil, tenetur magnam repellendus esse explicabo blanditiis? Dolorem quis at ipsam expedita magni laudantium eveniet illo iure sint doloribus?
          Ipsam deserunt fugiat expedita! Rerum ex, odio mollitia hic sequi, dolorem consequuntur, porro ad maxime consequatur commodi earum! Aliquam non provident velit nam quis iusto voluptas, nihil earum pariatur. Aut.
          Ex, voluptatibus molestiae, sint, dolor reiciendis perspiciatis dolores natus alias corrupti impedit libero quisquam consequatur dolorum ullam tempora corporis repellat modi adipisci non. Rerum est alias laboriosam debitis sit. Iste!
          Error, reiciendis quaerat sit magni nulla explicabo dolorum. Ratione quae voluptates ab fuga alias praesentium soluta consectetur quidem eius quas asperiores et provident eaque, officiis, debitis necessitatibus vel in ipsum.
          Consequuntur quas minus culpa aspernatur veniam doloribus asperiores cupiditate eaque accusamus rerum voluptates, eum, ullam ex dolores. Possimus ullam dolores dicta corrupti harum mollitia quaerat illo suscipit provident deserunt. Blanditiis!
          Numquam animi ab odio, explicabo quam sit iste nobis. Quae minima nulla iusto laborum obcaecati! Culpa eos dolores qui nam atque impedit. Provident perspiciatis distinctio a reiciendis corrupti nemo omnis?
          Rerum, cupiditate facilis harum fuga nemo dolorem praesentium nulla officia asperiores officiis reiciendis nam eligendi, maiores nostrum animi tempore modi, non repellendus? Ea molestiae dolores, quos tempore totam deserunt distinctio.
          Error iste ullam, aliquam beatae consequatur aspernatur laboriosam ea quae blanditiis dignissimos soluta dolore excepturi culpa deserunt mollitia id deleniti aliquid illo, voluptate voluptas voluptates. Ab minima adipisci aliquam at.
          Fugiat odit commodi incidunt explicabo. Cupiditate obcaecati debitis, molestiae doloremque at, optio distinctio provident, magni totam enim in eos? Nulla labore in neque maiores fuga quibusdam ipsum, impedit explicabo pariatur?
          Culpa ipsa, enim mollitia animi earum reiciendis ex sequi? Dicta ipsa mollitia numquam asperiores consequuntur aliquid laboriosam delectus cupiditate, quod suscipit hic eos cumque laborum! Ex debitis quasi suscipit itaque!
          Fuga earum ipsam quos modi quasi culpa alias repellat accusantium est molestiae. Tenetur molestias ipsa suscipit fugiat, porro excepturi facilis quaerat, quidem reiciendis quos voluptate eos vel incidunt fuga velit?
          Dolores iste, ut sed nulla perferendis dicta fugit quidem quibusdam, quisquam quae incidunt! Odio minima magni exercitationem totam culpa dolores maiores natus voluptas at tempora, assumenda odit accusantium sit autem.
          Ullam culpa quae cupiditate illum vel quia reprehenderit veniam quaerat possimus, earum unde deserunt recusandae odit repellat eaque accusantium fugiat at laboriosam mollitia voluptatum ducimus nesciunt excepturi nihil dignissimos. Architecto!
          Culpa nulla quisquam unde voluptatibus rem dignissimos iste necessitatibus aspernatur? Neque sed doloribus quasi omnis magni nisi, optio fuga expedita illum accusantium eaque repudiandae, maiores rem id in mollitia. Quibusdam.</p>
        <p className='text-semibold p-5'>Made by: Ethan Octavio McNaughton</p>
        </div>
        </>
    );
}